site_name: NGI-Stockholm Analysis Documentation
nav:
  - Home: index.md
  - Small RNA-seq: smrnaseq/index.md
theme: readthedocs
markdown_extensions:
  - tables
  - def_list
  - admonition
  - toc:
      permalink: true
